# Execution de test à chaque "push" #
name: python_test
on:
  push:
    branches:
      - main
jobs: # Tâches #
  build: # Environement de test #
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run tests # Exécution des tests avec unittest #
      run: |
        python -m unittest